datagrid:
    country:
        options:
            entityHint: country
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: Roca\Bundle\RefdataBundle\Entity\Country
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            isocode:
                label:     ISOCode
            maincountry:
                label:     maincountry
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html

        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
                isocode:
                    type:      string
                    label:     ISOCode
                    data_name: rd.isocode
                maincountry:
                    type:      boolean
                    label:     maincountry
                    data_name: rd.maincountry


        sorters:
            columns:
                code:
                    data_name: rd.code
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'

        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_rest_get
                params:
                    - id
                    - customEntityName
            delete_link:
                ype: url
                route: pim_customentity_rest_delete
                params:
                    - id
                    - customEntityName

        actions:
            edit:
                type:       navigate
                label:      designline.this.edit
                icon:       edit
                link:       edit_link
                rowAction:  true
            delete:
                type:       delete
                label:      designline.this.delete
                icon:       trash
                link:       delete_link
#
#        mass_actions:
#            delete:
#                type: delete
#                label: pim.grid.mass_action.delete
#                entity_name: designline
#                acl_resource: ~
#                handler: mass_delete
#                className: 'AknButton AknButton--important AknButtonList-item'
#                messages:
#                    confirm_title: pim_datagrid.mass_action.delete.confirm_title
#                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
#                    confirm_ok: pim_datagrid.mass_action.delete.confirm_ok
#                    success: pim_datagrid.mass_action.delete.success
#                    error: pim_datagrid.mass_action.delete.error
#                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
#
#            quick_export_csv:
#                type: export
#                label: pim.grid.mass_action.quick_export.csv_all
#                className:  'AknButton AknButton--action AknButtonList-item'
#                handler: custom_quick_export
#                route: pim_customentity_quickexport
#                route_parameters:
#                    customEntityName: designline
#                    _format: csv
#                    _contentType: text/csv
#                context:
#                    withHeader: true
#                messages:
#                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
