# /src/Acme/Bundle/AppBundle/Resources/config/datagrid.yml
datagrid:
    market:
        options:
            entityHint: market
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: Roca\Bundle\RefdataBundle\Entity\Market
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: code
            translation:
                label: description
#            locales.code:
#                label: locales
            webBaseUrl:
                label: webBaseUrl
            currency:
                label: currency
            mdmMarket:
                label: mdmMarket
            locales:
                label: locales

        properties:
            id: ~
            show_link:
                type: url
                route: pim_customentity_rest_get
                params:
                    - id
                    - customEntityName
            edit_link:
                type: url
                route: pim_customentity_rest_get
                params:
                    - id
                    - customEntityName
            delete_link:
                ype: url
                route: pim_customentity_rest_delete
                params:
                    - id
                    - customEntityName

        actions:
            edit:
                type:      navigate
                label:     Edit the reference data
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: Delete the reference data
                icon:  trash
                link:  delete_link
        filters:
            columns:
                code:
                    type:      string
                    label:     code
                    data_name: rd.code
                description:
                    type:      string
                    label:     Description
                    data_name: translation.description
                locales:
                    type:      string
                    label:     locales
                    data_name: rd.locales
        sorters:
            columns:
                code:
                    data_name: rd.code
                translation:
                    data_name: translation.description

            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'