extensions:

  pim-menu-reference_data-navigation-block:
    module: pim/menu/navigation-block
    parent: pim-menu-reference_data-column
    targetZone: navigation
    position: 10
    config:
      title: roca_custom.menu.item.reference_data.it

  roca_custon-menu-reference_data-navigation-block-manager:
    module: pim/menu/navigation-block
    parent: pim-menu-reference_data-column
    targetZone: navigation
    position: 120
    config:
      title: roca_custom.menu.item.reference_data.manager

  roca_custon-menu-reference_data-navigation-block-hierarchies:
    module: pim/menu/navigation-block
    parent: pim-menu-reference_data-column
    targetZone: navigation
    position: 130
    config:
      title: roca_custom.menu.item.reference_data.hierarchies

  roca_custom-menu-reference_data-item-brand:
    module: pim/menu/item
    parent: pim-menu-reference_data-navigation-block
    position: 10
    config:
      title: roca_custom.menu.item.reference_data.brand
      to: pim_customentity_index
      routeParams:
        customEntityName: brand

  roca_custom-menu-reference_data-item-country:
    module: pim/menu/item
    parent: pim-menu-reference_data-navigation-block
    position: 20
    config:
      title: roca_custom.menu.item.reference_data.country
      to: pim_customentity_index
      routeParams:
        customEntityName: country

  roca_custom-menu-reference_data-item-market:
    module: pim/menu/item
    parent: pim-menu-reference_data-navigation-block
    position: 30
    config:
      title: roca_custom.menu.item.reference_data.markets
      to: pim_customentity_index
      routeParams:
        customEntityName: market

# ???
#  roca_custom-menu-reference_data-item-resources:
#    module: pim/menu/item
#    parent: roca_custon-menu-reference_data-navigation-block-it
#    position: 40
#    config:
#      title: roca_custom.menu.item.reference_data.resources
#      to: pim_customentity_index
#      routeParams:
#        customEntityName: brand

  roca_custom-menu-reference_data-item-designer:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-manager
    position: 40
    config:
      title: roca_custom.menu.item.reference_data.designers
      to: pim_customentity_index
      routeParams:
        customEntityName: designer

  roca_custom-menu-reference_data-item-designline:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-manager
    position: 40
    config:
      title: roca_custom.menu.item.reference_data.designlines
      to: pim_customentity_index
      routeParams:
        customEntityName: designline

  roca_custom-menu-reference_data-item-distinction:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-manager
    position: 40
    config:
      title: roca_custom.menu.item.reference_data.distinctions
      to: pim_customentity_index
      routeParams:
        customEntityName: distinction

  roca_custom-menu-reference_data-item-emblematic_work:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-manager
    position: 40
    config:
      title: roca_custom.menu.item.reference_data.emblematic_works
      to: pim_customentity_index
      routeParams:
        customEntityName: emblematic_work

  roca_custom-menu-reference_data-item-finish:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-manager
    position: 40
    config:
      title: roca_custom.menu.item.reference_data.finish
      to: pim_customentity_index
      routeParams:
        customEntityName: finish

  roca_custom-menu-reference_data-item-solution:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-manager
    position: 40
    config:
      title: roca_custom.menu.item.reference_data.solutions
      to: pim_customentity_index
      routeParams:
        customEntityName: solution

  roca_custom-menu-reference_data-item-picto:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-manager
    position: 40
    config:
      title: roca_custom.menu.item.reference_data.pictos
      to: pim_customentity_index
      routeParams:
        customEntityName: picto

  roca_custom-menu-reference_data-item-selling:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-hierarchies
    position: 10
    config:
      title: roca_custom.menu.item.reference_data.sellings
      to: pim_customentity_index
      routeParams:
        customEntityName: selling

  roca_custom-menu-reference_data-item-search:
    module: pim/menu/item
    parent: roca_custon-menu-reference_data-navigation-block-hierarchies
    position: 20
    config:
      title: roca_custom.menu.item.reference_data.searchs
      to: pim_customentity_index
      routeParams:
        customEntityName: search
