Roca\Bundle\MarketizableBundle\Entity\Locale:
    type: entity
    table: pim_catalog_locale
    changeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\LocaleRepository
    fields:
        marketname:
            type: string
            length: 25
            nullable: true
        isamarket:
            type: boolean
