Roca\Bundle\RocaReferenceDataBundle\Entity\Supplier:
    type: entity
    table: rd_supplier
    changeTrackingPolicy: DEFERRED_EXPLICIT
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    fields:
      id:
        type: integer
        id: true
        generator:
          strategy: AUTO
      code:
        type: string
        length: 255
        nullable: false
        unique: true
      name:
        type: string
        length: 255
        nullable: false
      email:
        type: string
        length: 255
        nullable: false
