Roca\Bundle\RefdataBundle\Entity\EmblematicWorkTranslation:
    type: entity
    table: asm_emblematicwork_translation
    changeTrackingPolicy: DEFERRED_EXPLICIT
    uniqueConstraints:
        locale_foreign_key_idx:
            columns:
                - locale
                - foreign_key
    fields:
#    required
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
#    required
        locale:
            type: string
            length: 20

        name:
            type: string
            length: 100
            nullable: true
        lead:
            type: string
            length: 500
            nullable: true
        city:
            type: string
            length: 100
            nullable: true
        body:
            type: string
            length: 2000
            nullable: true

    manyToOne:
        foreignKey:
            targetEntity: Roca\Bundle\RefdataBundle\Entity\EmblematicWork
            inversedBy: translations
            joinColumns:
                foreign_key:
                    referencedColumnName: id
                    onDelete: CASCADE
