Roca\Bundle\RefdataBundle\Entity\SellingTranslation:
    type: entity
    table: asm_selling_translation
    changeTrackingPolicy: DEFERRED_EXPLICIT
    uniqueConstraints:
        locale_foreign_key_idx:
            columns:
                - locale
                - foreign_key
    fields:
        #    required
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        #    required
        locale:
            type: string
            length: 20

        description:
            type: string
            length: 100
            nullable: true
        lead:
            type: string
            length: 100
            nullable: true

    manyToOne:
        foreignKey:
            targetEntity: Roca\Bundle\RefdataBundle\Entity\Selling
            inversedBy: translations
            joinColumns:
                foreign_key:
                    referencedColumnName: id
                    onDelete: CASCADE
