akeneo_storage_utils:
    mapping_overrides:
        -
            original: Pim\Bundle\CatalogBundle\Entity\Locale
            override: Roca\Bundle\NlocaleBundle\Entity\Locale
#        -
#            original: PimEnterprise\Bundle\SecurityBundle\Entity\LocaleAccess
#            override: Roca\Bundle\MarketizableBundle\Entity\LocaleAccess
