parameters:
    pimee_enrich.form.type.locale.class: Roca\Bundle\NlocaleBundle\Form\Type\LocaleType

services:
    pim_enrich.form.type.locale:
      class: '%pimee_enrich.form.type.locale.class%'
      tags:
          - { name: form.type, alias: pimee_enrich_locale }
      calls:
          - [addEventSubscriber, ['@pimee_enrich.form.subscriber.locale_permissions']]