custom_entities:
    brand:
        entity_class: Roca\Bundle\RefdataBundle\Entity\Brand
        options:
            edit_form_extension: pim-brand-edit-form

    country:
        entity_class: Roca\Bundle\RefdataBundle\Entity\Country
        options:
            edit_form_extension: pim-country-edit-form

    designline:
        entity_class: Roca\Bundle\RefdataBundle\Entity\DesignLine
        options:
            edit_form_extension: pim-designline-edit-form

    designer:
        entity_class: Roca\Bundle\RefdataBundle\Entity\Designer
        options:
            edit_form_extension: pim-designer-edit-form

    market:
        entity_class: Roca\Bundle\RefdataBundle\Entity\Market
        options:
            edit_form_extension: pim-market-edit-form

    distinction:
        entity_class: Roca\Bundle\RefdataBundle\Entity\Distinction
        options:
            edit_form_extension: pim-distinction-edit-form

    solution:
        entity_class: Roca\Bundle\RefdataBundle\Entity\Solution
        options:
            edit_form_extension: pim-solution-edit-form

    emblematic_work:
        entity_class: Roca\Bundle\RefdataBundle\Entity\EmblematicWork
        options:
            edit_form_extension: pim-emblematic_work-edit-form

