services:
    roca.normalizer.brand:
        class: Roca\Bundle\RefdataBundle\Normalizer\BrandNormalizer
        tags:
            - {name: pim_serializer.normalizer, priority: 200}

    roca.normalizer.designline:
        class: Roca\Bundle\RefdataBundle\Normalizer\DesignLineNormalizer
        tags:
        - {name: pim_serializer.normalizer, priority: 200}
