parameters:
  pim_enrich.twig.locale_extension.class:       Pim\Bundle\EnrichBundle\Twig\LocaleExtension

services:
  # Twig extensions
  pim_enrich.twig.locale_extension:
    class: '%pim_enrich.twig.locale_extension.class%'
    arguments:
    - '@pim_user.context.user'
    tags:
    - { name: twig.extension }


