parameters:
    pim_enrich.normalizer.attribute.class:  Roca\Bundle\EnrichBundle\Normalizer\AttributeNormalizer
    pimee_enrich.normalizer.attribute.class: Roca\Bundle\EnrichBundle\Normalizer\AttributeNormalizer
services:
    pim_enrich.normalizer.attribute:
        class: '%pim_enrich.normalizer.attribute.class%'
        arguments:
            - '@pim_serializer'
            - '@pim_enrich.provider.field.chained'
            - '@pim_enrich.provider.empty_value.chained'
            - '@pim_enrich.provider.filter.chained'
            - '@pim_catalog.localization.localizer.number'

    pimee_enrich.normalizer.attribute:
        class: '%pimee_enrich.normalizer.attribute.class%'
        decorates: pim_enrich.normalizer.attribute
        decoration_inner_name: pim_enrich.normalizer.attribute.base
        arguments:
        - '@pim_enrich.normalizer.attribute.base'
        tags:
        - { name: pim_internal_api_serializer.normalizer }