# /src/Acme/Bundle/BlogBundle/Resources/config/form_extensions.yml

extensions:
  oro-system-config-tab-acme:
    module: pim/configuration/tab
    parent: oro-system-config-tabs
    targetZone: container
    position: 110