extensions:
  pim-country-index:
    module: pim/common/simple-view
    config:
      template: pim/template/common/default-template
    forwarded-events:
      grid_load:start: grid_load:start
      grid_load:complete: grid_load:complete

  pim-country-index-grid-container:
    module: pim/common/simple-view
    parent: pim-country-index
    targetZone: content
    config:
      template: pim/template/form/index/index

  pim-country-index-user-navigation:
    module: pim/menu/user-navigation
    parent: pim-country-index
    targetZone: user-menu
    config:
      userAccount: pim_menu.user.user_account
      logout: pim_menu.user.logout

  pim-country-index-grid-title:
    module: pim/common/grid-title
    parent: pim-country-index
    targetZone: title
    config:
      title: roca_custom.country.index_title

  pim-country-index-breadcrumbs:
    module: pim/common/breadcrumbs
    parent: pim-country-index
    targetZone: breadcrumbs
    config:
      tab: pim-menu-reference_data
      item: acme_custom-menu-reference_data-item-country

  pim-country-index-grid-filters-list:
    module: oro/datafilter/filters-list
    parent: pim-country-index-grid-container
    targetZone: filters

  pim-country-index-grid-filters-manage:
    module: oro/datafilter/filters-button
    parent: pim-country-index-grid-container
    targetZone: filters

  pim-country-index-mass-actions:
    module: pim/grid/mass-actions
    parent: pim-country-index
    targetZone: bottom-panel
    config:
      label: acme_custom.country.selected

  pim-country-index-actions-panel:
    module: oro/datagrid/actions-panel
    parent: pim-country-index-mass-actions
    targetZone: actions-panel

  pim-country-index-pagination:
    module: oro/datagrid/pagination-input
    parent: pim-country-index-grid-container
    targetZone: toolbar
    config:
      gridName: country

  pim-country-index-grid:
    module: pim/form/common/index/grid
    parent: pim-country-index
    targetZone: content
    position: 1000
    config:
      alias: country

  pim-country-index-create-button:
    module: pim/form/common/index/create-button
    parent: pim-country-index
    targetZone: buttons
    aclResourceId: pim_enrich_product_create
    config:
      title:     pim_custom_entity.button.create
      modalForm: pim-country-create-modal