measures_config:
    Pressure:
        standard: BAR
        units:
            BAR:
                convert: [{'mul': '1'}]
                symbol: Bar
            PASCAL:
                convert: [{'mul': '0.00001'}]
                symbol: Pa
            HECTOPASCAL:
                convert: [{'mul': '0.001'}]
                symbol: hPa
            KILOPASCAL:
                convert: [{'mul': '0.0001'}]
                symbol: KPa
            MILLIBAR:
                convert: [{'mul': '0.001'}]
                symbol: mBar
            ATM:
                convert: [{'mul': '0.986923'}]
                symbol: atm
            PSI:
                convert: [{'mul': '14.50376985373022'}]
                symbol: PSI
            TORR:
                convert: [{'mul': '750.06375541921'}]
                symbol: Torr
            MMHG:
                convert: [{'mul': '750.06375541921'}]
                symbol: mmHg
