extensions:
    pim-market-edit-form:
        module: custom_entity/form/common/edit-form

    pim-market-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-market-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: roca_custom-menu-reference_data-item-market

    pim-market-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-market-edit-form
        position: 1000

    pim-color-edit-form-label:
        module: custom_entity/form/common/label
        parent: pim-color-edit-form
        targetZone: title
        position: 90

    pim-market-edit-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-market-edit-form
        targetZone: content
        position: 100

    pim-market-edit-form-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-market-edit-form
        targetZone: buttons
        position: 50

    pim-market-edit-form-delete:
        module: custom_entity/form/common/delete
        parent: pim-market-edit-form-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_enrich_group_remove
        position: 100
        config:
            route: pim_customentity_rest_delete
            routeParams:
                customEntityName: market
            trans:
                title: roca_custom.message.confirmation.remove.market
                container: pim_enrich.confirmation.delete_item
                success: pim_custom_entity.message.confirmation.removed
                fail: pim_custom_entity.error.removing
            redirect: pim_customentity_index

    pim-market-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-market-edit-form
        targetZone: buttons
        position: 120

    pim-market-edit-form-save:
        module: custom_entity/form/common/save-form
        parent: pim-market-edit-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: roca_custom.market.info.update_successful
            updateFailureMessage: roca_custom.market.info.update_failed
            notReadyMessage: roca_custom.market.info.field_not_ready
            url: pim_customentity_rest_edit
            route_params:
                customEntityName: market
            redirectAfter: pim_customentity_rest_get
            excludedProperties: []

    pim-market-edit-form-properties-tab:
        module: pim/common/tab
        parent: pim-market-edit-form-form-tabs
        targetZone: container
        position: 100
        config:
            label: pim_custom_entity.form.tab.properties.title

    pim-market-edit-form-resources-tab:
        module: pim/common/tab
        parent: pim-market-edit-form-form-tabs
        targetZone: container
        position: 110
        config:
#            label: roca_custom_entity.form.tab.resources.title
            label: roca_test
            title: roca_test

    pim-market-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-market-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-market-edit-form-resources:
        module: pim/common/simple-view
        parent: pim-market-edit-form-resources-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-market-edit-form-history:
        module: pim/common/tab/history
        parent: pim-market-edit-form-form-tabs
        targetZone: container
        position: 120
        config:
            class: market
            title: pim_custom_entity.form.tab.history.title

    pim-market-edit-form-properties-common:
        module: pim/common/simple-view
        parent: pim-market-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_custom_entity.form.tab.properties.section.common
                dropZone: content

    pim-market-edit-form-resources-common:
        module: pim/common/simple-view
        parent: pim-market-edit-form-resources
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_custom_entity.form.tab.properties.section.common
                dropZone: content

    pim-market-edit-form-properties-code:
        module: pim/form/common/fields/text
        parent: pim-market-edit-form-properties-common
        targetZone: content
        position: 90
        config:
            fieldName: code
            label: roca_custom.market.field.label.code
            required: true
            readOnly: true

#    pim-market-edit-form-properties-name:
#        module: pim/form/common/fields/text
#        parent: pim-market-edit-form-properties-common
#        targetZone: content
#        position: 100
#        config:
#            fieldName: name
#            choiceNameField: code
#            choiceValueField: name
#            isCustomEntity: false
#            required: true

    pim-market-edit-form-properties-currency:
        module: pim/form/common/fields/text
        parent: pim-market-edit-form-properties-common
        targetZone: content
        position: 100
        config:
            fieldName: currency
            label: roca_custom.market.field.label.currency
            required: true
            readOnly: false

    pim-market-edit-form-properties-mdmMarket:
        module: pim/form/common/fields/boolean
        parent: pim-market-edit-form-properties-common
        targetZone: content
        position: 110
        config:
            fieldName: mdmMarket
            label: roca_custom.market.field.label.mdmMarket
            required: true
            readOnly: false

    pim-market-edit-form-properties-webBaseUrl:
        module: pim/form/common/fields/text
        parent: pim-market-edit-form-properties-common
        targetZone: content
        position: 120
        config:
            fieldName: webBaseUrl
            label: roca_custom.market.field.label.webBaseUrl
            required: true
            readOnly: false

