# Cloudinary Connector extension configuration
asmcloudinary_connector:
    settings:
        cloud_name:
            value: your_cloud_name
            scope: app
        api_key:
            value: your_api_key
            scope: app
        api_secret:
            value: your_secret_key
            scope: app
        environment_variable:
            value: ~
            scope: app
monolog:
    channels: ['cloudinary_connector']
    handlers:
        cloudinary_connector:
            type: stream
            path:  %kernel.logs_dir%/cloudinary_%kernel.environment%.log
            level: info
            channels: cloudinary_connector