config:
    paths:
        cloudinary_connector/system/configuration: cloudinaryconnector/js/form/system.js
        cloudinary_connector/template/system/group/configuration: cloudinaryconnector/js/templates/system/group/configuration.html
