extensions:
    pim-solution-create-modal:
        module: custom_entity/form/creation/modal
        config:
            labels:
               title: pim_custom_entity.create_popin.title
               subTitle: roca_custom.menu.item.reference_data.solution
            picture: illustrations/User.svg
            successMessage: pim_custom_entity.message.created
            editRoute: pim_customentity_rest_get
            postUrl:
                route: pim_customentity_rest_create
                parameters:
                    customEntityName: solution

    pim-solution-create-code:
        module: pim/form/common/creation/field
        parent: pim-solution-create-modal
        targetZone: fields
        position: 10
        config:
            identifier: code
            label: pim_custom_entity.form.field.label.code

    pim-solution-create-name:
        module: pim/form/common/creation/field
        parent: pim-solution-create-modal
        targetZone: fields
        position: 20
        config:
            identifier: name
            label: roca_custom.solution.field.label.name

    pim-solution-create-websort:
        module: pim/form/common/creation/field
        parent: pim-solution-create-modal
        targetZone: fields
        position: 40
        config:
            identifier: websort
            label: roca_custom.solution.field.label.websort

    ##Sección de Traducción
    pim-solution-edit-form-properties-translation-section:
        module: pim/common/simple-view
        parent: pim-solution-edit-form-properties
        targetZone: accordion
        position: 110
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_custom_entity.form.tab.properties.section.label_translations
                dropZone: content

    #Campos de traducción
    pim-solution-edit-form-properties-translation:
        module: pim/common/properties/translation
        parent: pim-solution-edit-form-properties-translation-section
        targetZone: content
        position: 100
        config:
            fieldBaseId: 'pim_enrich_group_form_label_'