datagrid:
    locale-grid:
        options:
            entityHint: locale
            manageFilters: false
        source:
            acl_resource: pim_enrich_locale_index
            type: pim_datasource_locale
        columns:
            marketname:
                label: Market Name
            code:
                label: Locale
            activated:
                label: Activated
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html
            isamarket:
                label: Is a Market
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html

        properties:
            id: ~
            edit_link:
                type: url
                route: pimee_enrich_locale_edit
                params:
                    - id
        actions:
            edit:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:         navigate
                label:        Edit locale
                link:         edit_link
                acl_resource: pimee_enrich_locale_edit_permissions
                rowAction:    true
        sorters:
            columns:
                code:
                    data_name: l.code
                activated:
                    data_name: l.activated
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                code:
                    type:      search
                    label:     Code
                    data_name: l.code
                activated:
                    type:      boolean
                    label:     Activated
                    data_name: l.activated
                isamarket:
                    type:      boolean
                    label:     Is a Market
                    data_name: l.activated
